---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyubao.
--- DateTime: 2021/11/11 18:02
---

---@class BehaviourTreeBlackboard
local BehaviourTreeBlackboard = SimpleClassUtil:class()

function BehaviourTreeBlackboard:initialize(contextManager)
    ---@type ContextManager
    self.ContextManager  = contextManager
    self.SkillPosX = nil
    self.SkillPosY = nil
    self.ConfigID = nil
    self.GUID = nil
    self.InheritPosX = nil
    self.InheritPosY = nil
    self.SourceEntityId  = nil
    self.TargetList = List.new()
    self.BehaviourTreeBlackboardParams = {}
    ---@type number[]
    self.SubUnit = List.new()
    self.RenderTargetList = List.new()
    self.IsManual = false
    self.IsCaptain = false
    self.IsMeleeSkill = false
    self.OriginFillData = nil
    self.Damage = 0
    ---@type QteData
    self.QteData = nil
    self.RemoveAbility = false
    ---@type BaseBuffData
    self.ListenBuffData = {}

end

return BehaviourTreeBlackboard