---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyubao.
--- DateTime: 2021/11/11 18:50
---
---@class BehaviourTreeAgent
---@field TreeType NewBattle.AttackTreeType
local BehaviourTreeAgent = SimpleClassUtil:class()

function BehaviourTreeAgent:initialize(owner)
    ---@type BaseEntity
    self.owner = owner
    self.AbilityID = 0
    self.ReleaseAbilityId = 0
    self.AbilityName = nil
    self.SourceEntityId = 0 ---攻击树记录技能来源
    self.TreeType = 0 ---树类型
    self._isBTDebug = nil
end

return BehaviourTreeAgent