---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyubao.
--- DateTime: 2021/11/11 15:28
---

Logger = require("lua.DreamGarden.Logger.Logger")
class = require("lua.DreamGarden.Base.MiddleClass")
SimpleClassUtil = require("lua.DreamGarden.Base.SimpleClassUtil")