---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyubao.
--- DateTime: 2021/11/11 16:14
---

local Global = _G.Global or SimpleClassUtil:class()

rawset(_G, "Global", Global)

g = Global