---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyubao.
--- DateTime: 2021/11/10 16:18
---
---
if DevPackagePath~=nil then return end
module("DevPackagePath", package.seeall)

package.path = string.gsub(package.path, "[^;]*Simulator[^;]*", "F:/myTest/my_test/my_test_lua/DreamGarden" .. "/?.lua")

function init()
    assureConfigIsRight()
    removeTmpFiles()
    -- change lua file search path: replace iPhone Simulator path with projectDir
    package.path = string.gsub(package.path, "[^;]*Simulator[^;]*", projectDir .. "/?.lua")
    local checkReloadFunc = (kIsLogTimeCost and checkPackageToReloadWithLogTime or checkPackageToReload)
    if kActivelyListenFileChange then
        -- local scheduler = cc.Director:getInstance():getScheduler()
        -- scheduler:scheduleScriptFunc(checkReloadFunc, kActivelyListenDt, false)
        local _tick = LuaScheduler:getInstance():schedule(checkReloadFunc ,kActivelyListenDt,false )
    end
    fileChangeTimeNote = {}
    fileIndex2ModuleNote = {}
    allFileArr = {}
    fileReadIndex = 1
    getAllFiles(projectDir, allFileArr)
    startTime = os.time()
end

--
--init()