---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyubao.
--- DateTime: 2021/11/10 14:23
---

------ 框架基础
require "lua.DreamGarden.Base.init_base"



------ 项目基础-- ** require "**.**Game.init_***_main"
require "lua.DreamGarden.HA.HAGame.init_HA_main"
