---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyubao.
--- DateTime: 2021/11/11 15:30
---

require "lua.DreamGarden.HA.HAGame.HAMain"

require "lua.DreamGarden.HA.Global.init_Global"

require "lua.DreamGarden.HA.Battle.init_Battle"