---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liuyubao.
--- DateTime: 2021/11/15 15:36
---
local BehaviorAnalysis = {}

function BehaviorAnalysis:Analysis()

    return
end

return BehaviorAnalysis